services:
  mysql:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts/:/docker-entrypoint-initdb.d
    restart: 'always'
    shm_size: 2gb
    env_file:
      - backend/.env
    ports:
      - "3306:3306"

volumes:
  db_data: