name: CI for python

on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: pytest

  # This is a relatively general and expensive linting process.
  # Keep this in mind before you throw this at everything.
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      
      # This will checkout the global linters under the organization .github directory.
      # If you want to use your own linters, comment this out.
      - name: Checkout .github repo for predefined linters
        uses: actions/checkout@v4
        with:
          repository: MaiikiruRepos/.github
          sparse-checkout: .github/linters
          path: .github/linters

      - name: Lint Code Base
        uses: github/super-linter@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
